version: '3.8'

volumes:
  grafana:
    driver: local
  prometheus:
    driver: local
  logs:
    driver: local

services:
  app:
    build: '.'
    ports:
      - "8080:8080"
    volumes:
      - logs:/var/log/app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VK_API_KEY=${VK_API_KEY}
      - VK_GROUP_ID=${VK_GROUP_ID}
      - VK_CONFIRMATION_STRING=${VK_CONFIRMATION_STRING}
      - VK_API_VERSION=${VK_API_VERSION}
      - VK_SECRET=${VK_SECRET}

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - "prometheus:prometheus"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    links:
      - "app:app"