server:
  port: ${PORT:8080}
  error:
    include-exception: true

spring:
  application:
    name: testvkbot
  profiles:
    active: "prod"
  main:
    banner-mode: off

management:
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoints:
    web:
      exposure:
        include: health,prometheus,info

logging:
  pattern:
    console: "%d [a:%X{accountId},c:%X{bot},r:%X{requestId}] %5p [%8c] - %m %n"
    file: "%d [a:%X{accountId},c:%X{bot},r:%X{requestId}] %5p [%8c] - %m %n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: "main.%d.%i.log.gz"
  file:
    name: ${log.dir:./logs}/app.main.log
  level:
    "dev.upersuser": info
    "org.springframework": warn

vk:
  groupId: ${VK_GROUP_ID}
  confirmationString: ${VK_CONFIRMATION_STRING}
  secret: ${VK_SECRET}
  apiKey: ${VK_API_KEY}
  apiVersion: ${VK_API_VERSION}

webclient:
  connectTimeout: ${WEB_CLIENT_CONNECT_TIMEOUT:5000}
  readTimeout: ${WEB_CLIENT_READ_TIMEOUT:5000}

